Elite: MacroTranslate Class Reference
MacroTranslate Class Reference
宏翻译器, 可以支持用户自定义宏
#include <MacroTranslate.h>
Public Member Functions
Node * Marco (Node *node_template, Node *args)
Private Member Functions
void marcoReplace (Node *node)
Node * findArg (const string &name)
Private Attributes
map< string, Node * > args_map
Detailed Description
宏翻译器, 可以支持用户自定义宏
宏翻译器, 应该说是宏展开器, 能够根据用户的定义, 将宏转换为真正的形式, 支持递归
Member Function Documentation
Node * MacroTranslate::findArg (const string & name) private
References args_map.
Referenced by marcoReplace().
Node * MacroTranslate::Marco (Node * node_template, Node * args)
References args_map, Node::copyChild(), Node::getChild(), Node::getNext(), Node::getStr(), and marcoReplace().
Referenced by CodeGenContext::MacroMake().
void MacroTranslate::marcoReplace (Node * node) private
References Node::copyChild(), findArg(), Node::getChild(), Node::getNext(), Node::getStr(), Node::isIDNode(), Node::replaceChild(), and Node::replaceNext().
Referenced by Marco().
Member Data Documentation
map< string, Node* > MacroTranslate::args_map private
Referenced by findArg(), and Marco().
The documentation for this class was generated from the following files:
RedApple/src/MacroTranslate.h
RedApple/src/MacroTranslate.cpp