Elite: Lex Class Reference
Lex Class Reference
Lex is the main controller for the system.
#include <Lex.h>
Public Member Functions
Lex ()
~Lex ()
virtual Token * Read ()
get the next token ,if it is done ,will return NULL it may throw exception, please try and catch it
virtual void Init (const char *pData=NULL)
initialize the Lex system, must be called before Read Token, it can also set the pData
bool ReadConfig (const char *path=NULL)
read the config, you need to call it manually before init system, it will find the lex.cfg at the ./ path
int AddRule (const char *pName, const char *pattern)
add a new Lex rule
int FindRule (const char *pName)
find the rule, will return the id of it.
virtual const char * getRule (int id)
find the rule name
virtual int getRuleSize ()
get the rules sum
void InitCore ()
init the main DFA core
const char * getData ()
virtual void setData (const char *pData)
不再初始化系统，只是简单的重设置输入字符流
DFA * getMainDFA ()
Private Member Functions
DFA * combineAllDFA ()
when you change the Rule, you should run it manually
int testin (vector< int > newvec, vector< vector< int > > statelist)
bool testequal (vector< int >, vector< int >)
void addStopState (vector< int > &, int)
void printvec (vector< int > v)
Private Attributes
DFA * mainDFA
Main dfa for all dfa combine to one.
DFACore * core
the core of main DFA
EquivalenceClass * pEClass
the Equivalence Class 等价类表
const char * pData = NULL
int pointer = 0
pointer for the data, it's always point to the next char need to be scan.
RuleManager * ruleManager
used to manage the rules
Detailed Description
Lex is the main controller for the system.
Constructor & Destructor Documentation
Lex::Lex ()
Lex::~Lex ()
Member Function Documentation
int Lex::AddRule (const char * pName, const char * pattern)
add a new Lex rule
void Lex::addStopState (vector< int > & newvec, int p) private
References Rule::dfa, DFA::isStopState(), and DFA::setStopState().
DFA * Lex::combineAllDFA () private
when you change the Rule, you should run it manually
References Rule::dfa, EquivalenceClass::getSum(), DFA::nextState(), and pEClass.
int Lex::FindRule (const char * pName)
find the rule, will return the id of it.
const char * Lex::getData ()
DFA * Lex::getMainDFA ()
const char * Lex::getRule (int id) virtual
find the rule name
Implements LexInterface.
References Rule::name.
int Lex::getRuleSize () virtual
get the rules sum
Implements LexInterface.
void Lex::Init (const char * pData = NULL) virtual
initialize the Lex system, must be called before Read Token, it can also set the pData
Implements LexInterface.
References pEClass.
Referenced by main().
void Lex::InitCore ()
init the main DFA core
References pEClass.
void Lex::printvec (vector< int > v) private
Token * Lex::Read () virtual
get the next token ,if it is done ,will return NULL it may throw exception, please try and catch it
Implements LexInterface.
Referenced by main().
bool Lex::ReadConfig (const char * path = NULL)
read the config, you need to call it manually before init system, it will find the lex.cfg at the ./ path
Referenced by Worker::CreateDefault(), and main().
void Lex::setData (const char * pData) virtual
不再初始化系统，只是简单的重设置输入字符流
Implements LexInterface.
bool Lex::testequal (vector< int > a, vector< int > b) private
int Lex::testin (vector< int > newvec, vector< vector< int > > statelist) private
Member Data Documentation
DFACore* Lex::core private
the core of main DFA
DFA* Lex::mainDFA private
Main dfa for all dfa combine to one.
const char* Lex::pData = NULL private
EquivalenceClass* Lex::pEClass private
the Equivalence Class 等价类表
int Lex::pointer = 0 private
pointer for the data, it's always point to the next char need to be scan.
RuleManager* Lex::ruleManager private
used to manage the rules
The documentation for this class was generated from the following files:
Lex/include/Lex.h
Lex/src/Lex.cpp