Elite: Regex Class Reference
Regex Class Reference
正则表达式类
#include <Regex.h>
Public Member Functions
Regex ()
~Regex ()
Regex (const estring &pattern, EquivalenceClass *pEClass)
bool init (const estring &pattern, EquivalenceClass *pEClass=NULL)
node * getRoot ()
void setEClass (EquivalenceClass *pEClass)
EquivalenceClass * getEClass ()
std::string getPattern ()
Private Member Functions
void run (echar_t c)
CharSet * makeEscape ()
void doCharSet (CharSet *)
void doOperater (echar_t)
void operate ()
void putOperater (echar_t c)
void push (echar_t c)
void pop ()
Private Attributes
estring pattern
int pointer = 0
node * root
std::stack< echar_t > operater_stack
std::stack< node * > obj_stack
EquivalenceClass * pEClass
estring tempSet
estring tempLeftInt
estring tempRightInt
bool isEnd = false
Detailed Description
正则表达式类
Constructor & Destructor Documentation
Regex::Regex ()
Regex::~Regex ()
References root.
Regex::Regex (const estring & pattern, EquivalenceClass * pEClass)
References init().
Member Function Documentation
void Regex::doCharSet (CharSet * pSet) private
References EquivalenceClass::Add(), isEnd, obj_stack, pEClass, and push().
Referenced by run().
void Regex::doOperater (echar_t c) private
EquivalenceClass * Regex::getEClass () inline
References pEClass.
std::string Regex::getPattern () inline
References estring::to_utf8().
node* Regex::getRoot () inline
References root.
bool Regex::init (const estring & pattern, EquivalenceClass * pEClass = NULL)
References estring::length(), obj_stack, operater_stack, pattern, pointer, pop(), root, run(), and setEClass().
Referenced by Regex().
CharSet * Regex::makeEscape () private
References CharSet::insert(), pattern, and pointer.
Referenced by run().
void Regex::operate () private
References obj_stack, and operater_stack.
void Regex::pop () private
References obj_stack, and operater_stack.
Referenced by init(), and push().
void Regex::push (echar_t c) private
References operater_stack, and pop().
Referenced by doCharSet(), and run().
void Regex::putOperater (echar_t c) private
References obj_stack.
Referenced by run().
void Regex::run (echar_t c) inline private
References estring::clear(), doCharSet(), CharSet::insert(), isEnd, makeEscape(), operater_stack, push(), estring::push_back(), putOperater(), tempLeftInt, tempRightInt, and tempSet.
Referenced by init().
void Regex::setEClass (EquivalenceClass * pEClass) inline
References pEClass.
Referenced by init().
Member Data Documentation
bool Regex::isEnd = false private
Referenced by doCharSet(), and run().
std::stack<node*> Regex::obj_stack private
Referenced by doCharSet(), init(), operate(), pop(), and putOperater().
std::stack<echar_t> Regex::operater_stack private
Referenced by init(), operate(), pop(), push(), and run().
estring Regex::pattern private
Referenced by init(), and makeEscape().
EquivalenceClass* Regex::pEClass private
Referenced by doCharSet(), getEClass(), and setEClass().
int Regex::pointer = 0 private
Referenced by init(), and makeEscape().
node* Regex::root private
Referenced by getRoot(), init(), and ~Regex().
estring Regex::tempLeftInt private
Referenced by run().
estring Regex::tempRightInt private
Referenced by run().
estring Regex::tempSet private
Referenced by run().
The documentation for this class was generated from the following files:
Lex/include/Regex.h
Lex/src/Regex.cpp