Elite: CodeGenContext Class Reference
CodeGenContext Class Reference
代码生成上下文, 是代码生成中的关键信息存储类
#include <CodeGenContext.h>
Public Member Functions
CodeGenContext (Node *node)
~CodeGenContext ()
void PreMacro ()
预先扫描宏时的初始化，初始化第一趟扫描
void PreInit ()
预先扫描类型名称时的初始化，初始化第二趟扫描
void PreTypeInit ()
预先扫描类型和函数定义时的初始化，初始化第三趟扫描
void Init ()
正式扫描前的初始化
LValue MacroMake (Node *node)
这个函数是用来一条条翻译Node宏的
void MacroMakeAll (Node *node)
递归翻译该节点下的所有宏
ICodeGenFunction * getMacro (const string &str)
查找一个名称是否为一个C宏
void AddOrReplaceMacros (const FuncReg *macro_funcs)
添加或替换一条宏
void AddOrReplaceMacros (const string &name, ICodeGenFunction *func)
void RemoveAllMacros ()
移除全部宏指令
LValue getFunction (Node *node)
LValue getFunction (const std::string &name)
void nowFunction (LValue _nowFunc)
shared_ptr< MacroModel > getUserMacro (const std::string &name)
void setUserMacro (const std::string &name, Node *node)
shared_ptr< FunctionModel > getFunctionModel (const std::string &name)
shared_ptr< StructModel > getStructModel (const std::string &name)
void ScanOther (Node *node)
void DefType (string name, LValue t)
LValue FindType (const string &name)
LValue FindType (Node *)
LValue FindSrcType (const string &name)
LValue FindSrcType (Node *)
void DefVar (const string &name, LValue addr)
定义一个变量 有可能是全局变量
LValue FindVar (const string &name)
在符号表中查找一个变量
void SaveMacros ()
void RecoverMacros ()
bool isSave ()
void setIsSave (bool save)
id * FindST (Node *node) const
id * FindST (const string &str) const
llcg * getLLCG ()
获取低层次代码生成器，目前只有llvm
Public Attributes
IDTable * st
Private Member Functions
void setNormalType ()
Private Attributes
llcg * codeGenerator
Node * root
语法树根节点
map< string, ICodeGenFunction * > macro_map
宏定义表，用来查找是否有该宏定义的
stack< map< string,
ICodeGenFunction * > > macro_save_stack
这个栈是用来临时保存上面的查询表的
bool _save
Detailed Description
代码生成上下文, 是代码生成中的关键信息存储类
存储最关键的数据, 例如符号栈, LLVM生成器对象. 在宏翻译过程中, 该上下文指针将会传入翻译函数中.
该上下文在编译器中, 同一时刻应该仅存在一份, 生存周期为一个包的编译开始到包内全部代码翻译完毕.
切换上下文时, 相当于清空符号栈, 释放资源, 重启LLVM后端 会导致之前分析的符号全部消失
Constructor & Destructor Documentation
CodeGenContext::CodeGenContext (Node * node)
References llcg::CreateLLVM(), and root.
CodeGenContext::~CodeGenContext ()
Member Function Documentation
void CodeGenContext::AddOrReplaceMacros (const FuncReg * macro_funcs)
添加或替换一条宏
添加或替换一条宏，如果当前名称存在则替换，没有则添加
Parameters
macro_funcs 一组宏定义数组，类似Lua中函数的定义方式
References _funcReg::func, macro_funcs, and _funcReg::name.
Referenced by class_macro(), function_macro(), and test2_elite_plugin_init().
void CodeGenContext::AddOrReplaceMacros (const string & name, ICodeGenFunction * func)
void CodeGenContext::DefType (string name, LValue t)
References type_t.
void CodeGenContext::DefVar (const string & name, LValue addr)
定义一个变量 有可能是全局变量
Parameters
name 变量名
addr 存储地址
References var_t.
Referenced by set_macro().
LValue CodeGenContext::FindSrcType (const string & name)
References id::data, StructModel::getStruct(), struct_t, id::type, and type_t.
Referenced by new_macro().
LValue CodeGenContext::FindSrcType (Node * node)
References Node::getStr().
id * CodeGenContext::FindST (Node * node) const
References Node::getStr().
id * CodeGenContext::FindST (const string & str) const
LValue CodeGenContext::FindType (const string & name)
Referenced by StructModel::genCode(), FunctionModel::genCode(), and TypeNode::typeGen().
LValue CodeGenContext::FindType (Node * node)
References Node::getStr().
LValue CodeGenContext::FindVar (const string & name)
在符号表中查找一个变量
Parameters
name 变量名
Returns
变量的存储地址
References id::data, id::type, and var_t.
Referenced by IDNode::codeGen().
LValue CodeGenContext::getFunction (Node * node)
References Node::getStr().
Referenced by call_macro().
LValue CodeGenContext::getFunction (const std::string & name)
shared_ptr< FunctionModel > CodeGenContext::getFunctionModel (const std::string & name)
References id::data, function_t, and id::type.
Referenced by function_macro().
llcg* CodeGenContext::getLLCG () inline
获取低层次代码生成器，目前只有llvm
Returns
生成器指针
Referenced by call_macro(), IntNode::codeGen(), FloatNode::codeGen(), IDNode::codeGen(), StringNode::codeGen(), for_macro(), function_macro(), StructModel::genCode(), FunctionModel::genCode(), StructModel::genMetaCode(), FunctionModel::genMetaCode(), FunctionModel::getFunction(), StructModel::getStruct(), if_macro(), new_macro(), opt1_macro(), opt2_macro(), return_macro(), select_macro(), set_macro(), and while_macro().
ICodeGenFunction * CodeGenContext::getMacro (const string & str)
查找一个名称是否为一个C宏
查找一个名称是否为一个C宏
Parameters
str 宏的名字
Returns
如果有，则返回函数指针，否则返回NULL
shared_ptr< StructModel > CodeGenContext::getStructModel (const std::string & name)
References id::data, struct_t, and id::type.
Referenced by opt2_macro(), and struct_macro().
shared_ptr< MacroModel > CodeGenContext::getUserMacro (const std::string & name)
References id::data, macro_t, and id::type.
void CodeGenContext::Init ()
正式扫描前的初始化
References macro_classes, and macro_funcs.
bool CodeGenContext::isSave () inline
Referenced by IDNode::codeGen(), opt2_macro(), and select_macro().
LValue CodeGenContext::MacroMake (Node * node)
这个函数是用来一条条翻译Node宏的
这个函数是用来一条条翻译Node宏的
Parameters
node 要翻译的语法节点
Returns
翻译后的后端变量，往往是一个表达式或一个语句返回的值
References ICodeGenFunction::call(), Node::FreeAll(), Node::getChild(), Node::getNext(), Node::getStr(), Node::isIDNode(), MacroTranslate::Marco(), and Node::print().
Referenced by Node::codeGen(), for_macro(), function_macro(), if_macro(), and while_macro().
void CodeGenContext::MacroMakeAll (Node * node) inline
递归翻译该节点下的所有宏
Parameters
node 要翻译的节点
void CodeGenContext::nowFunction (LValue _nowFunc)
void CodeGenContext::PreInit ()
预先扫描类型名称时的初始化，初始化第二趟扫描
References macro_prescan.
void CodeGenContext::PreMacro ()
预先扫描宏时的初始化，初始化第一趟扫描
References macro_defmacro.
void CodeGenContext::PreTypeInit ()
预先扫描类型和函数定义时的初始化，初始化第三趟扫描
References macro_pretype.
void CodeGenContext::RecoverMacros ()
Referenced by class_macro(), and function_macro().
void CodeGenContext::RemoveAllMacros ()
移除全部宏指令
移除全部宏指令
void CodeGenContext::SaveMacros ()
Referenced by class_macro(), and function_macro().
void CodeGenContext::ScanOther (Node * node)
void CodeGenContext::setIsSave (bool save) inline
Referenced by opt1_macro(), opt2_macro(), and select_macro().
void CodeGenContext::setNormalType () private
void CodeGenContext::setUserMacro (const std::string & name, Node * node)
References macro_t.
Referenced by defmacro_macro().
Member Data Documentation
bool CodeGenContext::_save private
用来记录当前是读取还是存入状态
llcg* CodeGenContext::codeGenerator private
map<string, ICodeGenFunction*> CodeGenContext::macro_map private
宏定义表，用来查找是否有该宏定义的
宏定义表，里面存放有对应名称的C语言宏处理函数
stack<map<string, ICodeGenFunction*> > CodeGenContext::macro_save_stack private
这个栈是用来临时保存上面的查询表的
某些情况，可能会对宏处理的函数进行临时的变更，就需要保存和恢复全部的状态，这个栈是用来记录宏表的
Node* CodeGenContext::root private
语法树根节点
额外保存的语法树根节点，为方便树的遍历而记录
IDTable* CodeGenContext::st
Referenced by function_type_macro(), StructModel::insertToST(), FunctionModel::insertToST(), and struct_type_macro().
The documentation for this class was generated from the following files:
RedApple/includes/CodeGenContext.h
RedApple/src/CodeGenContext.cpp