Elite: DFACore Class Reference
DFACore Class Reference
#include <DFACore.h>
Public Member Functions
DFACore ()
~DFACore ()
DFACore (DFA *_dfa, EquivalenceClass *_pEClass)
void Init (DFA *_dfa, EquivalenceClass *_pEClass)
void setData (const char *pData)
Token * Read ()
Private Member Functions
void getNextLine (int point)
Private Attributes
DFA * dfa
int state
estring tokendata
estring data
std::string outdata
std::string nowline
int point
int row_point
int line_point
Token * t = NULL
EquivalenceClass * pEClass
Constructor & Destructor Documentation
DFACore::DFACore () inline
DFACore::~DFACore () inline
References t.
DFACore::DFACore (DFA * _dfa, EquivalenceClass * _pEClass) inline
References Init().
Member Function Documentation
void DFACore::getNextLine (int point) private
References data, estring::length(), nowline, point, estring::substr(), and estring::to_utf8().
Referenced by Read(), and setData().
void DFACore::Init (DFA * _dfa, EquivalenceClass * _pEClass) inline
References dfa, line_point, pEClass, point, and row_point.
Referenced by DFACore().
Token * DFACore::Read ()
References estring::clear(), Token::col_num, data, Token::debug_line, dfa, EquivalenceClass::getClass(), getNextLine(), DFA::isStopState(), estring::length(), line_point, DFA::nextState(), nowline, outdata, pEClass, point, Token::pToken, estring::push_back(), Token::row_num, row_point, state, t, estring::to_utf8(), tokendata, and Token::type.
void DFACore::setData (const char * pData) inline
References data, and getNextLine().
Member Data Documentation
estring DFACore::data private
Referenced by getNextLine(), Read(), and setData().
DFA* DFACore::dfa private
Referenced by Init(), and Read().
int DFACore::line_point private
Referenced by Init(), and Read().
std::string DFACore::nowline private
Referenced by getNextLine(), and Read().
std::string DFACore::outdata private
Referenced by Read().
EquivalenceClass* DFACore::pEClass private
Referenced by Init(), and Read().
int DFACore::point private
Referenced by getNextLine(), Init(), and Read().
int DFACore::row_point private
Referenced by Init(), and Read().
int DFACore::state private
Referenced by Read().
Token* DFACore::t = NULL private
Referenced by Read(), and ~DFACore().
estring DFACore::tokendata private
Referenced by Read().
The documentation for this class was generated from the following files:
Lex/include/DFACore.h
Lex/src/DFACore.cpp