Elite: LRTable Class Reference
LRTable Class Reference abstract
#include <LRTable.h>
Public Member Functions
virtual void BuildTable (vector< ItemCollection * >)=0
virtual char ACTION (int, int)=0
virtual int GOTO (int, int)=0
virtual void printTable ()=0
Member Function Documentation
virtual char LRTable::ACTION (int , int) pure virtual
Implemented in LALRTable.
Referenced by LRCore::Run().
virtual void LRTable::BuildTable (vector< ItemCollection * >) pure virtual
Implemented in LALRTable.
virtual int LRTable::GOTO (int , int) pure virtual
Implemented in LALRTable.
Referenced by LRCore::Run().
virtual void LRTable::printTable () pure virtual
Implemented in LALRTable.
Referenced by LR_parser::Parse().
The documentation for this class was generated from the following file:
LR_Scanner/src/LRTable.h