Elite: LALRTable Class Reference
LALRTable Class Reference
#include <LALRTable.h>
Public Member Functions
LALRTable (int _constSum, int _stateSum, int _VSum, BNFParser *bnfparser)
LALRTable (const LALRTable &other)
~LALRTable ()
LALRTable & operator= (const LALRTable &other)
bool operator== (const LALRTable &other)
virtual void BuildTable (vector< ItemCollection * >)
virtual char ACTION (int, int)
virtual int GOTO (int, int)
virtual void printTable ()
void Save (const char *path)
void Load (const char *path)
Private Member Functions
bool PdPriority (int id, int c, const Item &item)
void BuildReduce (int id, const set< Item > &itemset)
template<class Archive >
void serialize (Archive &ar)
Private Attributes
int constSum
int stateSum
int VSum
vector< vector< int > > Goto
vector< vector< char > > Action
BNFParser * bnfparser
Friends
class cereal::access
Constructor & Destructor Documentation
LALRTable::LALRTable (int _constSum, int _stateSum, int _VSum, BNFParser * bnfparser)
References Action, bnfparser, constSum, Goto, stateSum, and VSum.
LALRTable::LALRTable (const LALRTable & other)
LALRTable::~LALRTable ()
Member Function Documentation
char LALRTable::ACTION (int state, int id) virtual
Implements LRTable.
References Action, constSum, and stateSum.
Referenced by printTable().
void LALRTable::BuildReduce (int id, const set< Item > & itemset) private
References Action, Goto, and PdPriority().
Referenced by BuildTable().
void LALRTable::BuildTable (vector< ItemCollection * > LALRItems) virtual
Implements LRTable.
References Action, BuildReduce(), constSum, ItemCollection::getID(), ItemCollection::GOTO(), Goto, and VSum.
Referenced by LR_parser::BuildParser().
int LALRTable::GOTO (int state, int id) virtual
Implements LRTable.
References Goto, stateSum, and VSum.
Referenced by printTable().
void LALRTable::Load (const char * path)
Referenced by LR_parser::BuildParser().
LALRTable & LALRTable::operator= (const LALRTable & other)
bool LALRTable::operator== (const LALRTable & other)
bool LALRTable::PdPriority (int id, int c, const Item & item) private
References bnfparser, constSum, BNFParser::getAssociativity(), Item::getBNF(), BNF::getBNFdata(), and BNFParser::getPrecedence().
Referenced by BuildReduce().
void LALRTable::printTable () virtual
Implements LRTable.
References ACTION(), GOTO(), DebugMsg::parser_dbg(), stateSum, and VSum.
void LALRTable::Save (const char * path)
Referenced by LR_parser::BuildParser().
template<class Archive > void LALRTable::serialize (Archive & ar) inline private
References Action, Goto, and stateSum.
Friends And Related Function Documentation
friend class cereal::access friend
Member Data Documentation
vector< vector <char> > LALRTable::Action private
Referenced by ACTION(), BuildReduce(), BuildTable(), LALRTable(), and serialize().
BNFParser* LALRTable::bnfparser private
Referenced by LALRTable(), and PdPriority().
int LALRTable::constSum private
Referenced by ACTION(), BuildTable(), LALRTable(), and PdPriority().
vector< vector <int> > LALRTable::Goto private
Referenced by BuildReduce(), BuildTable(), GOTO(), LALRTable(), and serialize().
int LALRTable::stateSum private
Referenced by ACTION(), GOTO(), LALRTable(), printTable(), and serialize().
int LALRTable::VSum private
Referenced by BuildTable(), GOTO(), LALRTable(), and printTable().
The documentation for this class was generated from the following files:
LR_Scanner/src/LALRTable.h
LR_Scanner/src/LALRTable.cpp