Elite: PackageLoader Class Reference
PackageLoader Class Reference
扩展包加载器
#include <PackageLoader.h>
Public Member Functions
PackageLoader (const string &base_path, MetaScriptRunner *msr)
~PackageLoader ()
void FindAll ()
找出目录下所以的可加载项
void LoadDefault ()
加载全部默认需要加载的包
Private Attributes
string base_path
map< string, EPackage * > packages
MetaScriptRunner * msr
Detailed Description
扩展包加载器
Constructor & Destructor Documentation
PackageLoader::PackageLoader (const string & base_path, MetaScriptRunner * msr)
PackageLoader::~PackageLoader ()
Member Function Documentation
void PackageLoader::FindAll ()
找出目录下所以的可加载项
References FileUtils::dir_traversal(), and FileUtils::only_dir.
Referenced by MetaScriptRunner::setUpLoader().
void PackageLoader::LoadDefault ()
加载全部默认需要加载的包
References PackageJIT::AddSymbol(), and HelloWorld().
Referenced by MetaScriptRunner::setUpLoader().
Member Data Documentation
string PackageLoader::base_path private
MetaScriptRunner* PackageLoader::msr private
map<string, EPackage*> PackageLoader::packages private
The documentation for this class was generated from the following files:
MetaScriptRunner/include/PackageLoader.h
MetaScriptRunner/src/PackageLoader.cpp