Elite: IDTable Class Reference
IDTable Class Reference
简易栈式符号表，需要在进入函数后手动压栈等操作
#include <idtable.h>
Public Member Functions
IDTable ()
const id * find (string) const
void insert (string, id *)
void push ()
void pop ()
int getLevel ()
IDTable ()
id * find (const string &str) const
查找元素是否在符号表中
map< string, id * > & getAll (int level)
返回一层的全部元素
void insert (const string &str, SymbolType type, LValue data)
插入一个元素
void push ()
压栈，一般在进入新的符号区域，例如函数体中
void pop ()
弹栈，在离开一个符号区域时需要手动调用
int getLevel ()
获取当前层级
Private Attributes
deque< IDMap > ID_stack
Detailed Description
简易栈式符号表，需要在进入函数后手动压栈等操作
Constructor & Destructor Documentation
IDTable::IDTable ()
References ID_stack.
IDTable::IDTable ()
Member Function Documentation
const id * IDTable::find (string idname) const
References IDMap::find(), and ID_stack.
Referenced by find_id(), function_type_macro(), save_id(), and struct_type_macro().
id * IDTable::find (const string & str) const
查找元素是否在符号表中
查找元素是否在当前符号表中，若当前符号栈不只一层，还好向上层符号表进行查找
Parameters
str 要查找的符号名
Returns
若找到，返回id结构体的指针，无需释放内存。未找到返回NULL
References IDMap::find(), and ID_stack.
map< string, id * > & IDTable::getAll (int level)
返回一层的全部元素
Parameters
level 返回一层的全部元素，level是传入的层级
Returns
返回的元素map
References ID_stack.
int IDTable::getLevel ()
References ID_stack.
Referenced by insert(), make_code(), and save_id().
int IDTable::getLevel ()
获取当前层级
void IDTable::insert (string str, id * pid)
References ID_stack, and IDMap::insert().
Referenced by StructModel::insertToST(), FunctionModel::insertToST(), and save_id().
void IDTable::insert (const string & str, SymbolType type, LValue data)
插入一个元素
Parameters
str 要插入的名称
type 类型的枚举
data 数据指针
References getLevel(), ID_stack, and IDMap::insert().
void IDTable::pop ()
References ID_stack.
Referenced by pop_stack().
void IDTable::pop ()
弹栈，在离开一个符号区域时需要手动调用
void IDTable::push ()
References ID_stack.
Referenced by push_stack().
void IDTable::push ()
压栈，一般在进入新的符号区域，例如函数体中
Member Data Documentation
deque< IDMap > IDTable::ID_stack private
Referenced by find(), getAll(), getLevel(), IDTable(), insert(), pop(), and push().
The documentation for this class was generated from the following files:
LR_Scanner/src/idtable.h
LR_Scanner/src/idtable.cpp