Elite: PathGetter Class Reference
PathGetter Class Reference
路径获取类, 可以获取环境变量, 工具链的路径等
#include <PathGetter.h>
Static Public Member Functions
static const char * getEliteHome ()
static const char * getEliteLibPath ()
static const char * getEliteCfgPath ()
static const char * getEliteToolsPath ()
static const char * getElitePackagesPath ()
static const char * getDefaultLexCfg ()
static const char * getDefaultParserCfg ()
static const char * getNowPath ()
static bool testFile (const char *file)
static PathGetter_Private * getInstance ()
Private Member Functions
PathGetter ()
~PathGetter ()
Static Private Attributes
static PathGetter_Private * instance = NULL
Detailed Description
路径获取类, 可以获取环境变量, 工具链的路径等
Constructor & Destructor Documentation
PathGetter::PathGetter () private
PathGetter::~PathGetter () private
Member Function Documentation
const char * PathGetter::getDefaultLexCfg () static
References PathGetter_Private::elite_lex_path, and getInstance().
Referenced by Builder::Builder(), and main().
const char * PathGetter::getDefaultParserCfg () static
References PathGetter_Private::elite_parser_path, and getInstance().
Referenced by Builder::Builder(), and main().
const char * PathGetter::getEliteCfgPath () static
References PathGetter_Private::elite_cfg_path, and getInstance().
const char * PathGetter::getEliteHome () static
References PathGetter_Private::elite_home, and getInstance().
const char * PathGetter::getEliteLibPath () static
References PathGetter_Private::elite_lib_path, and getInstance().
const char * PathGetter::getElitePackagesPath () static
References PathGetter_Private::elite_packages_path, and getInstance().
Referenced by Builder::Builder(), and main().
const char * PathGetter::getEliteToolsPath () static
References PathGetter_Private::elite_tools_path, and getInstance().
Referenced by Builder::call_ld(), and Builder::call_llc().
PathGetter_Private * PathGetter::getInstance () static
References instance, and PathGetter_Private::setPath().
Referenced by getDefaultLexCfg(), getDefaultParserCfg(), getEliteCfgPath(), getEliteHome(), getEliteLibPath(), getElitePackagesPath(), getEliteToolsPath(), and getNowPath().
const char * PathGetter::getNowPath () static
References PathGetter_Private::elite_now_path, and getInstance().
Referenced by main().
bool PathGetter::testFile (const char * file) static
References FileUtils::test_file().
Referenced by Builder::BuildFile().
Member Data Documentation
PathGetter_Private * PathGetter::instance = NULL static private
Referenced by getInstance().
The documentation for this class was generated from the following files:
Builder/include/PathGetter.h
Builder/src/PathGetter.cpp