Elite: FileUtils Class Reference
FileUtils Class Reference
跨平台的文件系统接口
#include <FileUtils.h>
Public Types
enum traversal_type { all, only_file, only_dir }
Static Public Member Functions
static int create_directory (const std::string &path, bool IgnoreExisting=true)
static bool isNeedUpdate (const std::string &cfg_path, const std::string &save_path)
static bool test_dir (const std::string &path)
static bool test_file (const std::string &path)
static std::string get_current_path ()
static std::string fileReader (const char *path)
static int dir_traversal (const std::string &path, IFileTraversal &ifile, traversal_type t)
static int dir_recursive_traversal (const std::string &path, IFileTraversal &ifile, traversal_type t)
Detailed Description
跨平台的文件系统接口
Member Enumeration Documentation
enum FileUtils::traversal_type
Enumerator
all
only_file
only_dir
Member Function Documentation
int FileUtils::create_directory (const std::string & path, bool IgnoreExisting = true) static
Referenced by Builder::SetBuildPath().
int FileUtils::dir_recursive_traversal (const std::string & path, IFileTraversal & ifile, traversal_type t) static
References IFileTraversal::Work().
int FileUtils::dir_traversal (const std::string & path, IFileTraversal & ifile, traversal_type t) static
References IFileTraversal::Work().
Referenced by PackageLoader::FindAll(), and EPackage::Load().
std::string FileUtils::fileReader (const char * path) static
Referenced by Builder::BuildFile(), and EPackage::EPackage().
string FileUtils::get_current_path () static
Referenced by PathGetter_Private::setPath().
bool FileUtils::isNeedUpdate (const std::string & cfg_path, const std::string & save_path) static
Referenced by LR_parser::BuildParser().
bool FileUtils::test_dir (const std::string & path) static
Referenced by PathGetter_Private::setPath().
bool FileUtils::test_file (const std::string & path) static
Referenced by PathGetter_Private::setPath(), PathGetter::testFile(), and DirFileTraversal::Work().
The documentation for this class was generated from the following files:
ExIconv/include/FileUtils.h
ExIconv/src/FileUtils.cpp