Elite: ScriptRunner Class Reference
ScriptRunner Class Reference
脚本解析器类(其实这个类应该放到MetaScriptRunner中)
#include <ScriptRunner.h>
Public Member Functions
virtual void Init ()
virtual int MakeEnv (const char *, Grammer_Node *)
virtual int MakeNewLuaTable (Token *t)
virtual int Run (int &, char *, Grammer_Node *)
virtual void Finished ()
virtual void ClearEnv ()
virtual void RunLine (const char *line)
virtual Node * getRoot ()
virtual vector< pair< string,
Grammer_Node * > > & getEnv ()
virtual struct lua_State * getLuaState ()
bool isRunMeta ()
void setRunMeta (bool b)
Protected Member Functions
ScriptRunner ()
~ScriptRunner ()
char * addFunction (char *data)
Protected Attributes
struct lua_State * L = NULL
vector< pair< string,
Grammer_Node * > > env
bool runMeta
Detailed Description
脚本解析器类(其实这个类应该放到MetaScriptRunner中)
Constructor & Destructor Documentation
ScriptRunner::ScriptRunner () protected
References runMeta.
ScriptRunner::~ScriptRunner () protected
References L.
Member Function Documentation
char * ScriptRunner::addFunction (char * data) protected
References env.
Referenced by Run().
void ScriptRunner::ClearEnv () virtual
References env.
Referenced by LRCore::Reduce().
void ScriptRunner::Finished () virtual
Reimplemented in MetaScriptRunner, and PCodeScriptRunner.
Referenced by LRCore::Run().
vector< pair< string, Grammer_Node * > > & ScriptRunner::getEnv () virtual
References env.
Referenced by CallFunc().
lua_State * ScriptRunner::getLuaState () virtual
References L.
Node * ScriptRunner::getRoot () virtual
Reimplemented in MetaScriptRunner.
Referenced by Worker::Run().
void ScriptRunner::Init () virtual
Reimplemented in MetaScriptRunner, and PCodeScriptRunner.
References getLuaFunc(), and L.
Referenced by PCodeScriptRunner::Init(), MetaScriptRunner::Init(), and LRCore::Run().
bool ScriptRunner::isRunMeta () inline
int ScriptRunner::MakeEnv (const char * name, Grammer_Node * node) virtual
References env.
Referenced by LRCore::Reduce().
int ScriptRunner::MakeNewLuaTable (Token * t) virtual
References L, Token::pToken, and Token::type.
Referenced by LRCore::Shift().
int ScriptRunner::Run (int & code, char * data, Grammer_Node * node) virtual
References addFunction(), cachecode, CallFunc(), L, and Grammer_Node::lua_data.
Referenced by LRCore::Reduce().
void ScriptRunner::RunLine (const char * line) virtual
References L, and runMeta.
Referenced by LRCore::TokenFliter().
void ScriptRunner::setRunMeta (bool b) inline
Member Data Documentation
vector< pair<string, Grammer_Node*> > ScriptRunner::env protected
Referenced by addFunction(), ClearEnv(), getEnv(), and MakeEnv().
struct lua_State* ScriptRunner::L = NULL protected
Referenced by getLuaState(), PCodeScriptRunner::Init(), Init(), MetaScriptRunner::Init(), MakeNewLuaTable(), Run(), RunLine(), and ~ScriptRunner().
bool ScriptRunner::runMeta protected
Referenced by RunLine(), and ScriptRunner().
The documentation for this class was generated from the following files:
LR_Scanner/includes/ScriptRunner.h
LR_Scanner/src/ScriptRunner.cpp