Elite: Item Class Reference
Item Class Reference
#include <Item.h>
Public Member Functions
Item ()
Item (const Item &other)
~Item ()
bool operator< (const Item &other) const
Item & operator= (const Item &other)
bool operator== (const Item &other) const
Item & operator++ ()
Item (BNF *_bnf, int _itempoint)
void setItem (BNF *_bnf, int _itempoint)
void addLookahead (int p)
void setLookahead (const set< int > &pset)
void removeLookahead (int p)
const set< int > & getLookahead () const
int getNowID () const
bool isNULL () const
int getSize () const
const BNF * getBNF () const
int getItempoint () const
Private Attributes
int itempoint
BNF * bnf
set< int > lookahead
Constructor & Destructor Documentation
Item::Item ()
References bnf, and itempoint.
Item::Item (const Item & other)
References bnf, getLookahead(), itempoint, and lookahead.
Item::~Item ()
Item::Item (BNF * _bnf, int _itempoint)
References setItem().
Member Function Documentation
void Item::addLookahead (int p) inline
Referenced by ItemCollection::CLOSURE1(), ItemCollection::MakeLR0Items(), ItemCollection::MakeSpreadMap(), and SpreadLookahead().
const BNF* Item::getBNF () const inline
Referenced by LALRTable::PdPriority(), printSetFrom(), and ItemCollection::printSpread().
int Item::getItempoint () const inline
Referenced by ItemCollection::CLOSURE1(), printSetFrom(), and ItemCollection::printSpread().
const set<int>& Item::getLookahead () const inline
Referenced by ItemCollection::CLOSURE1(), Item(), ItemCollection::MakeSpreadMap(), and printSetFrom().
int Item::getNowID () const inline
References State::id.
Referenced by ItemCollection::CLOSURE0(), ItemCollection::CLOSURE1(), ItemCollection::MakeItemCollection(), and ItemCollection::MakeSpreadMap().
int Item::getSize () const inline
Referenced by ItemCollection::CLOSURE1().
bool Item::isNULL () const inline
Item& Item::operator++ () inline
bool Item::operator< (const Item & other) const
References bnf, and itempoint.
Item & Item::operator= (const Item & other)
References bnf, itempoint, and lookahead.
bool Item::operator== (const Item & other) const
References bnf, and itempoint.
void Item::removeLookahead (int p) inline
Referenced by ItemCollection::MakeSpreadMap().
void Item::setItem (BNF * _bnf, int _itempoint)
References bnf, and itempoint.
Referenced by Item().
void Item::setLookahead (const set< int > & pset) inline
Referenced by ItemCollection::MakeLookahead(), and SpreadLookahead().
Member Data Documentation
BNF* Item::bnf private
Referenced by Item(), operator<(), operator=(), operator==(), and setItem().
int Item::itempoint private
Referenced by Item(), operator<(), operator=(), operator==(), and setItem().
set<int> Item::lookahead private
Referenced by Item(), and operator=().
The documentation for this class was generated from the following files:
LR_Scanner/src/Item.h
LR_Scanner/src/Item.cpp