Elite: BNF Class Reference
BNF Class Reference
#include <BNF.h>
Public Member Functions
BNF ()
~BNF ()
void print_bnf () const
void print_bnf (int) const
void addBNFdata (State *_s)
void setRoot (State *_s)
State * getRoot () const
const vector< State * > & getBNFdata () const
void setID (int _id)
int getID () const
char * getScript ()
int & getScriptCode ()
Static Public Member Functions
static vector< BNF * > BuildAllBNF (State *, VMap &)
Static Protected Member Functions
static void BuildFromNode (State *, VMap &)
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Private Attributes
int id
State * root
vector< State * > BNFdata
char * bnf_script
int scriptcode
Static Private Attributes
static int temp_size
static vector< BNF * > bnfs
Friends
class cereal::access
Constructor & Destructor Documentation
BNF::BNF () inline
Referenced by BuildFromNode().
BNF::~BNF () inline
Member Function Documentation
void BNF::addBNFdata (State * _s) inline
Referenced by LR_parser::ExtendBNF().
vector< BNF * > BNF::BuildAllBNF (State * root, VMap & vmap) static
References bnfs, State::brother, BuildFromNode(), State::children, VMap::constMax, VMap::constSize, getRoot(), VMap::InsertVn(), setID(), State::state_class, and temp_size.
Referenced by LR_parser::AddBNF().
void BNF::BuildFromNode (State * node, VMap & vmap) static protected
References BNF(), bnf_script, BNFdata, bnfs, State::brother, State::children, constant, epsilon, VMap::InsertConst(), State::isList, root, script, State::script, State::state_class, State::state_const, State::state_type, temp_size, and temporality.
Referenced by BuildAllBNF().
const vector<State*>& BNF::getBNFdata () const inline
Referenced by LR_parser::MakeID(), ItemCollection::MakeNULLABLE(), LALRTable::PdPriority(), and LRCore::Reduce().
int BNF::getID () const inline
State* BNF::getRoot () const inline
References root.
Referenced by BuildAllBNF(), ItemCollection::findItems(), LR_parser::MakeID(), ItemCollection::MakeNULLABLE(), and LRCore::Reduce().
char* BNF::getScript () inline
Referenced by LRCore::Reduce().
int& BNF::getScriptCode () inline
Referenced by LRCore::Reduce().
void BNF::print_bnf () const
Referenced by printSetFrom(), ItemCollection::printSpread(), and LRCore::Reduce().
void BNF::print_bnf (int point) const
References BNFdata, constant, State::id, DebugMsg::parser_dbg(), root, State::state_class, State::state_const, and State::state_type.
template<class Archive > void BNF::serialize (Archive & ar) inline private
References root, and script.
void BNF::setID (int _id) inline
Referenced by BuildAllBNF(), and LR_parser::ExtendBNF().
void BNF::setRoot (State * _s) inline
References root.
Referenced by LR_parser::ExtendBNF().
Friends And Related Function Documentation
friend class cereal::access friend
Member Data Documentation
char* BNF::bnf_script private
Referenced by BuildFromNode().
vector<State*> BNF::BNFdata private
Referenced by BuildFromNode(), and print_bnf().
vector< BNF * > BNF::bnfs static private
Referenced by BuildAllBNF(), and BuildFromNode().
int BNF::id private
State* BNF::root private
Referenced by BuildFromNode(), and print_bnf().
int BNF::scriptcode private
int BNF::temp_size static private
Referenced by BuildAllBNF(), and BuildFromNode().
The documentation for this class was generated from the following files:
LR_Scanner/src/BNF.h
LR_Scanner/src/BNF.cpp