Elite: Worker Class Reference
Worker Class Reference
工作流类, 是词法分析器, 语法分析器, 元脚本解析器, 后端代码生成器整合后的工作流
#include <Worker.h>
Public Member Functions
void Init (LexInterface *l, Parser *p, ScriptRunner *s, CodeGen *c)
void Run (const char *input, const char *output)
void MetaGen (const char *output)
LexInterface * getLex ()
Parser * getParser ()
ScriptRunner * getScriptRunner ()
CodeGen * getCodegen ()
Worker ()
~Worker ()
Static Public Member Functions
static Worker * CreateDefault (const char *lex_cfg, const char *parser_cfg, const char *package_path)
static Worker * Create (LexInterface *l, Parser *p, ScriptRunner *s, CodeGen *c)
Protected Attributes
LexInterface * lex
Parser * parser
ScriptRunner * script_runner
CodeGen * codegen
Detailed Description
工作流类, 是词法分析器, 语法分析器, 元脚本解析器, 后端代码生成器整合后的工作流
Constructor & Destructor Documentation
Worker::Worker ()
Referenced by Create().
Worker::~Worker ()
Member Function Documentation
Worker * Worker::Create (LexInterface * l, Parser * p, ScriptRunner * s, CodeGen * c) static
References Init(), and Worker().
Referenced by CreateDefault().
Worker * Worker::CreateDefault (const char * lex_cfg, const char * parser_cfg, const char * package_path) static
References Parser::AddBNF(), RedCodeGen::Create(), Create(), MetaScriptRunner::Create(), RedCodeGen::getContext(), RedCodeGen::Init(), Parser::NewLRParser(), Lex::ReadConfig(), MetaScriptRunner::setCodeGenContext(), Parser::setLex(), Parser::setScriptRunner(), and MetaScriptRunner::setUpLoader().
Referenced by Builder::Builder(), and main().
CodeGen* Worker::getCodegen () inline
References codegen.
LexInterface* Worker::getLex () inline
References lex.
Parser* Worker::getParser () inline
References parser.
ScriptRunner* Worker::getScriptRunner () inline
References script_runner.
void Worker::Init (LexInterface * l, Parser * p, ScriptRunner * s, CodeGen * c)
References Parser::BuildParser(), codegen, LexInterface::Init(), lex, parser, and script_runner.
Referenced by Create().
void Worker::MetaGen (const char * output)
References codegen, and CodeGen::MakeMeta().
void Worker::Run (const char * input, const char * output)
References codegen, ScriptRunner::getRoot(), lex, CodeGen::Make(), Grammer_Node::NewNode(), Parser::Parse(), parser, CodeGen::PreScan(), Node::print(), root, script_runner, and LexInterface::setData().
Member Data Documentation
CodeGen* Worker::codegen protected
Referenced by getCodegen(), Init(), MetaGen(), and Run().
LexInterface* Worker::lex protected
Referenced by getLex(), Init(), and Run().
Parser* Worker::parser protected
Referenced by getParser(), Init(), and Run().
ScriptRunner* Worker::script_runner protected
Referenced by getScriptRunner(), Init(), and Run().
The documentation for this class was generated from the following files:
Builder/include/Worker.h
Builder/src/Worker.cpp