Elite: lvalue Class Reference
lvalue Class Reference
代替LLVM中Value的类，可供返回部分自定义数据，例如整数有无符号等信息
#include <lvalue.h>
Public Member Functions
virtual bool isStructType ()
virtual LValue getType ()
virtual string getTypeName ()
virtual LValue getPointerTo ()
Detailed Description
代替LLVM中Value的类，可供返回部分自定义数据，例如整数有无符号等信息
Member Function Documentation
virtual LValue lvalue::getPointerTo () inline virtual
Reimplemented in llvm_type.
Referenced by llcg_llvm::l_NewArray().
virtual LValue lvalue::getType () inline virtual
Referenced by llcg_llvm::l_Cmp(), and llcg_llvm::l_Opt2().
virtual string lvalue::getTypeName () inline virtual
Reimplemented in llvm_type, and llvm_value.
virtual bool lvalue::isStructType () inline virtual
Reimplemented in llvm_type.
The documentation for this class was generated from the following file:
RedApple/includes/LLCG/lvalue.h