Elite: RedApple/src/LLCG/LLVMLIB/llcg_llvm.cpp File Reference
llcg_llvm.cpp File Reference
#include "llcg_llvm.h"
#include "llvm_value.h"
#include "llvm_type.h"
Functions
static Value * getCast (Value *v, Type *t, BasicBlock *bb)
static void normalize_type (Value *&v1, Value *&v2, BasicBlock *bb)
Variables
const LibFunc stdlibs []
const LibFunc metalibs []
Function Documentation
static Value* getCast (Value * v, Type * t, BasicBlock * bb) static
Referenced by normalize_type().
static void normalize_type (Value *& v1, Value *& v2, BasicBlock * bb) static
References getCast().
Referenced by llcg_llvm::Cmp(), and llcg_llvm::Opt2().
Variable Documentation
const LibFunc metalibs[]
Referenced by llcg_llvm::register_metalib().
const LibFunc stdlibs[]
Referenced by llcg_llvm::BeginModule().