Elite: packages/test2/cplug/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "CodeGenContext.h"
#include "Model/nodes.h"
Functions
static LValue hello_macro (CodeGenContext *context, Node *node)
CodeGenContext * getCtx ()
void HelloWorld ()
void test2_elite_plugin_init (CodeGenContext *context)
Variables
static const FuncReg macro_funcs []
Function Documentation
CodeGenContext* getCtx ()
static LValue hello_macro (CodeGenContext * context, Node * node) static
void HelloWorld ()
Referenced by test2_elite_plugin_init().
void test2_elite_plugin_init (CodeGenContext * context)
References CodeGenContext::AddOrReplaceMacros(), HelloWorld(), and macro_funcs.
Variable Documentation
const FuncReg macro_funcs[] static
Initial value:
= {
    {"hello", hello_macro},
    {NULL, NULL}
}
Referenced by test2_elite_plugin_init().