Elite: VMap Struct Reference
VMap Struct Reference
#include <VMap.h>
Public Member Functions
int InsertVn (const char *s)
int getVn (const char *s)
void InsertVt (const char *s, int id)
int getVt (const char *s)
int InsertConst (const char *s)
int getConst (const char *s)
void print (map< string, int > &V)
void printAll ()
int VnIDtoIndex (int p)
template<class Archive >
void serialize (Archive &ar)
Public Attributes
map< string, int > VnMap
map< string, int > VtMap
map< string, int > ConstMap
int constSize = 0
int constMax = 0
Member Function Documentation
int VMap::getConst (const char * s) inline
Referenced by LR_parser::MakeID(), BNFParser::MakePrecedence(), and LRCore::TokenFliter().
int VMap::getVn (const char * s) inline
Referenced by LR_parser::MakeID().
int VMap::getVt (const char * s) inline
Referenced by LR_parser::MakeID(), and BNFParser::MakePrecedence().
int VMap::InsertConst (const char * s) inline
Referenced by BNF::BuildFromNode().
int VMap::InsertVn (const char * s) inline
Referenced by BNF::BuildAllBNF(), and LR_parser::ExtendBNF().
void VMap::InsertVt (const char * s, int id) inline
Referenced by LR_parser::AddBNF().
void VMap::print (map< string, int > & V) inline
References DebugMsg::parser_dbg().
void VMap::printAll () inline
References DebugMsg::parser_dbg().
Referenced by LR_parser::Parse().
template<class Archive > void VMap::serialize (Archive & ar) inline
int VMap::VnIDtoIndex (int p) inline
Member Data Documentation
map<string, int> VMap::ConstMap
int VMap::constMax = 0
Referenced by BNF::BuildAllBNF(), and LR_parser::BuildParser().
int VMap::constSize = 0
Referenced by LR_parser::AddBNF(), BNF::BuildAllBNF(), LR_parser::BuildParser(), ItemCollection::MakeLR0Items(), LR_parser::print_GOTO(), and ItemCollection::setVmap().
map<string, int> VMap::VnMap
map<string, int> VMap::VtMap
The documentation for this struct was generated from the following file:
LR_Scanner/src/VMap.h